#pragma once
#include <iostream>
#include <string>
#include <fstream>
#include <document.h>
#include <filereadstream.h>
#include <map>
#include <unordered_map>
#include <vector>
#include <iterator>
#include <algorithm>
#include <sstream>
#include <memory>
#include <clocale>
#include <regex>
#include <filesystem>
#include <stringbuffer.h>
#include <writer.h>

#include <Utils.h>
